services:

  amneziawg-exporter:
    build: .
    container_name: amneziawg-exporter
    hostname: amneziawg-exporter
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      AWG_EXPORTER_REDIS_HOST: amneziawg-exporter-redis
      AWG_EXPORTER_DOCKER_CONTAINERS: amnezia-wg,amnezia-wg2
    ports:
      - 9351:9351

  amneziawg-exporter-redis:
    image: redis:alpine
    container_name: amneziawg-exporter-redis
    restart: always
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
      - ./redis-data:/data
    ports:
      - "6379:6379"
